# Generated by Django 5.2.13 on 2026-04-23 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('STAFF', 'STAFF')], default='USER', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=20)),
                ('token_version', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserGenrePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_genre_preferences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_genres',
            field=models.ManyToManyField(blank=True, through='users.UserGenrePreference', to='catalogues.genre'),
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('method_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway_customer_id', models.CharField(max_length=128)),
                ('gateway_token', models.CharField(max_length=128)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_payment_methods',
                'indexes': [models.Index(fields=['user'], name='saved_payme_user_id_af14b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usergenrepreference',
            constraint=models.UniqueConstraint(fields=('user', 'genre'), name='uniq_user_genre_preference'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
    ]
