# Generated by Django 5.2.13 on 2026-04-23 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='actor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.genre'),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, through='catalogues.MovieGenre', to='catalogues.genre'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogues.movie'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='catalogues.hall'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showtimes', to='catalogues.hall'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='showtimes', to='catalogues.movie'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='catalogues.movie'),
        ),
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='moviegenre',
            constraint=models.UniqueConstraint(fields=('movie', 'genre'), name='uniq_movie_genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['is_active'], name='movies_is_acti_b4a45a_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['hall'], name='seats_hall_id_67d84f_idx'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('hall', 'row_label', 'seat_number'), name='uniq_hall_seat'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['movie', 'start_time'], name='showtimes_movie_i_0e6407_idx'),
        ),
        migrations.AddIndex(
            model_name='showtime',
            index=models.Index(fields=['hall', 'start_time'], name='showtimes_hall_id_baada1_idx'),
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='showtime_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='uniq_user_movie_rating'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 10)), name='rating_score_1_10'),
        ),
    ]
