# Generated by Django 5.2.13 on 2026-04-23 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_group_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('USED', 'USED'), ('EXPIRED', 'EXPIRED')], default='PENDING', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qr_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('payment_token', models.CharField(blank=True, max_length=128)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_group_id', models.UUIDField(blank=True, null=True)),
                ('result', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entry_logs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('IN_APP', 'IN_APP')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='PendingRefund',
            fields=[
                ('refund_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_group_id', models.UUIDField(db_index=True)),
                ('payment_token', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_refunds',
            },
        ),
    ]
