# Generated by Django 5.2.13 on 2026-04-23 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogues.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='catalogues.showtime'),
        ),
    ]
